version: '3.4'

services:
  db:
    image: 'postgres:10.1-alpine'
    environment:
      POSTGRES_USER: 'bookshare'
      POSTGRES_PASSWORD: 'yourpassword'
    volumes:
      - 'db:/var/lib/postgresql/data'

  cache:
    image: 'redis:4.0-alpine'
    command: 'redis-server --requirepass yourpassword'
    volumes:
      - 'cache:/var/lib/redis/data'

  api:
    image: '${API_IMAGE}'
    command: cat Gemfile.lock
    command: rails s
    build:
      context: .
      target: '${API_BUILD_TARGET}'
    depends_on:
      - 'db'
      - 'cache'
    ports:
      - "3000:3000"
    volumes:
      - '.:/usr/src/api'
      - '/usr/src/api/vendor/bundle'
    env_file:
      - '.env'

volumes:
  db:
  cache:
  dependencies:
