version: '3.4'

services:
  db:
    image: 'postgres:10.1-alpine'
    environment:
      POSTGRES_USER: 'bookshare'
      POSTGRES_PASSWORD: 'yourpassword'
    volumes:
      - 'db:/var/lib/postgresql/data'

  api:
    image: '${API_IMAGE}'
    build:
      context: .
      target: '${API_BUILD_TARGET}'
    depends_on:
      - 'db'
    ports:
      - "3000:3000"
    volumes:
      - '.:/usr/src/api'
      - '/usr/src/api/vendor/bundle'
    env_file:
      - '.env'

volumes:
  db:
