version: '3.4'

services:
  db:
    image: 'postgres:10.1-alpine'
    environment:
      POSTGRES_USER: 'bookshare'
      POSTGRES_PASSWORD: 'yourpassword'
    volumes:
      - 'db:/var/lib/postgresql/data'

  api:
    build: .
    depends_on:
      - 'db'
    ports:
      - "3000:3000"
    volumes:
      - '.:/usr/src/api'
    env_file:
      - '.env'

volumes:
  db: