# PostgreSQL. Versions 9.1 and up are supported.

development:
  url: <%= ENV['DATABASE_URL'].gsub('?', '_development?') %>

test:
  url: <%= ENV['DATABASE_URL'].gsub('?', '_test?') %>

production:
  url: <%= ENV['DATABASE_URL'].gsub('?', '_production?') %>
