class AdvertisementsController < ApiController
  before_action :require_login, except: [:index, :show, :show_by_user]
  rescue_from ActiveRecord::RecordNotFound, :with => :return_404

  # CUSTOM FUNCTIONS

  # POST /advertisements/feed
  # returns only open advertisements from other users
  def feed
    user_feed = Advertisement.where(status: Advertisement.open).where.not(user: current_user)
    render json: { 
      user: { username: current_user.username, email: current_user.email, name: current_user.name }, feed: user_feed },
      :include => {:user => { :only => [:id,:username, :name, :email] }},
      :except => :user_id
  end

  # GET /advertisements/user/1
  def show_by_user
    @advertisements = Advertisement.where('user_id = ?', params[:id])
    render json: @advertisements
  end

  # /advertisements/user/my
  def show_mine
    advertisement = Advertisement.where(user: current_user)
    render json: {
      advertisement: advertisement,
      user: current_user
    }
  end

  # POST /advertisements/close
  def close
    advertisement = Advertisement.find(params[:id])
    if current_user == advertisement.user
      if advertisement.closed!
        render json: {
          message: 'Closed succesfully',
          advertisement: advertisement
        }, status => 200
      else
        render json: {
          message: 'Could not save to database',
          advertisement: advertisement
        }, status => 500
      end

    else
      render json: {
          message: 'Unauthorized',
          advertisement: advertisement
        }, status => 401
    end
  end

  # AUTOMATICALLY GENERATED BY SCAFFOLD

  def index
    advertisement = Advertisement.all    
    render json: {advertisement: advertisement}
  end

  def show
    advertisement = Advertisement.find(params[:id])
    advertisement_user = advertisement.user
    render json: {advertisement: advertisement, 
                  username: advertisement_user.username,
                 }
  end

  # POST /advertisements
  def create
    
    advertisement = Advertisement.new(advertisement_params)
    advertisement.user = current_user
    if advertisement.save
      render json: {
        message: 'ok',
        advertisement: advertisement
      }
    else
      render json: {message: 'Could not create advertisement'}
    end
  end

  # PATCH/PUT /advertisements/1
  def update
    advertisement = Advertisement.find(params[:id])
    advertisement.user = current_user
    if advertisement.update(advertisement_params)
      render json: {message:'ok', advertisement: advertisement}
    else
      render json: {message: 'Could not update advertisement'}
    end
  end

  # DELETE /advertisements/1
  # def destroy
  #   advertisement = Advertisement.find(params[:id])
  #   advertisement.destroy
  # end

  def return_404
    render :json => {:error => "not-found"}.to_json, :status => 404
  end

  private
    def advertisement_params
      params.require(:advertisement).permit(:book_title, :book_author, :book_publication, :comment, :status)
    end
end
